return {
  { -- Bufferline
    'akinsho/bufferline.nvim',
    version = '*',
    dependencies = {
      'moll/vim-bbye',
      'nvim-tree/nvim-web-devicons',
    },
    config = function()
      require('bufferline').setup {
        options = {
          mode = 'buffers',
          style_preset = require('bufferline').style_preset.default,
          themable = true,
          numbers = 'none',
          close_command = 'bdelete! %d',
          right_mouse_command = 'bdelete! %d',
          left_mouse_command = 'buffer %d',
          middle_mouse_command = nil,
          indicator = {
            icon = '▎',
            style = 'none',
          },
          buffer_close_icon = '󰅖',
          modified_icon = '● ',
          close_icon = ' ',
          left_trunc_marker = ' ',
          right_trunc_marker = ' ',
          max_name_length = 32,
          max_prefix_length = 32,
          truncate_names = true,
          tab_size = 16,
          diagnostics = false,
          diagnostics_update_in_insert = false,
          diagnostics_update_on_event = true,
          color_icons = true,
          show_buffer_icons = true,
          show_buffer_close_icons = true,
          show_close_icon = true,
          show_tab_indicators = false,
          persist_buffer_sort = true,
          move_wraps_at_ends = false,
          separator_style = { '│', '│' },
          enforce_regular_tabs = true,
          always_show_bufferline = true,
          sort_by = 'insert_at_end',
          path_components = 1,
          icon_pinned = '󰐃',
          minimum_padding = 1,
          maximum_padding = 5,
          maximum_length = 15,
        },
        highlights = {
          separator = {
            fg = '#ffffff',
          },
          buffer_selected = {
            bold = true,
            italic = false,
          },
          -- separator_selected = {},
          -- tab_selected = {},
          -- background = {},
          -- indicator_selected = {},
          -- fill = {},
        },
      }
    end,
  },
}
